### ISSUE TITLE
../../../node_modules/@types/tar/index.d.ts:239:36 - error TS2709: Cannot use namespace 'MiniPass' as a type.

### ISSUE THREAD

**Issue by donewiththedollar** [scramjetorg/platform-samples#17]
```
ubuntu@ip-172-26-6-12:~/platform-samples/typescript/slack-write$ npm run build

> @scramjet/slack-write@0.0.1 build
> tsc -p tsconfig.json

../../../node_modules/@types/tar/index.d.ts:239:36 - error TS2709: Cannot use namespace 'MiniPass' as a type.

239 export interface ReadEntry extends MiniPass, HeaderProperties {
                                       ~~~~~~~~


Found 1 error in ../../../node_modules/@types/tar/index.d.ts:239

npm ERR! Lifecycle script `build` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @scramjet/slack-write@0.0.1 
npm ERR!   at location: /home/ubuntu/platform-samples/typescript/slack-write 
```

I tried to override the version for minipass but I have yet to find a way to work around this. Anyone figure this out? Appears minipass updated and this project will no longer work without it being updated as the tar cannot be read properly.

**Comment by MichalCz** [comment]
Hi @donewiththedollar,

We'll check and get back to you.

**Comment by MichalCz** [comment]
So I did check and it seems to work on my end...

Now I do see `../../../node_modules` - this would be higher up than platform_samples, so in `/home/ubuntu/`

Can you try the following:

1. Get a clean clone (either by `git clone` or `git clean -fdx`).
2. Enter the directory and run `npm i` - this will install the deps
3. Enter the directory and run `npm run build` - this will build the samples

You can enter either the `platform-samples` or `platform-samples/typescript/slack-write` - that doesn't matter.

Perhaps you could try just running the following commands:

```
cd /home/ubuntu/platform-samples/typescript/slack-write && \
   npm i && \
   npm run build
```

Let's see if that gets you somewhere...

**Comment by donewiththedollar** [comment]
Hey I did get it to work! Thanks for the quick response. I did a clean install, and all worked well!
