### ISSUE TITLE
Npm install

### ISSUE THREAD

**Issue by piotrek6641** [scramjetorg/platform-samples#37]
I am unable to install dependencies using node 18.14.0 and npm 9.3.1, after changing to node version 16 everything works as expected.
![Screenshot from 2023-02-06 15-06-06](https://user-images.githubusercontent.com/53794300/217007898-32f10258-379f-4e56-8cfe-abd093469cce.png)

**Comment by a-tylenda** [comment]
Resolved with https://github.com/scramjetorg/platform-samples/pull/38, Thanks piotrek6641!
